### ISSUE TITLE
Bug with C-style comments in OKL files.

### ISSUE THREAD

**Issue by ReidAtcheson** [tcew/OCCA2#33]
I will give screenshots of the affected lines.

With these lines code compiles and my tests all pass.
![screen shot 2015-01-31 at 2 47 30 pm](https://cloud.githubusercontent.com/assets/2857424/5989770/20ffccb2-a958-11e4-9fa1-fb333e6c317c.png)

However if I add a C-style comment like so:

![screen shot 2015-01-31 at 2 49 20 pm](https://cloud.githubusercontent.com/assets/2857424/5989781/71559da4-a958-11e4-9dbc-06dfa2f21b87.png)

I get the following errors

![screen shot 2015-01-31 at 2 49 50 pm](https://cloud.githubusercontent.com/assets/2857424/5989783/79b9e810-a958-11e4-9d1b-623ce07a8562.png)

Looking at the relevant cached OCCA file I find:

![screen shot 2015-01-31 at 2 50 53 pm](https://cloud.githubusercontent.com/assets/2857424/5989791/97bba39e-a958-11e4-83e5-1f82451dd3e3.png)

**Comment by ReidAtcheson** [comment]
I should mention: the same problem does not happen with C++ style inline comments (using //).

**Comment by dmed256** [comment]
Thanks! 
Fixed on commit [9ac0cd06e]
