### ISSUE TITLE
Don't ignore floopy failures

### ISSUE THREAD

**Issue by inducer** [tcew/OCCA2#35]
Here's a log of running gNUMA with a (f)loopy kernel:

```
Found cached binary of [occa/clusterVerticalStrongVolumeKernel.occa] in [/exthome/andreas/._occa/f51421d852343e72]
floopy --lang=floopy --target=cl:0,0  --occa-defines=/exthome/andreas/._occa/loopy1_7d27af49ef7c8cc7.defs  --occa-add-dummy-arg occa/verticalStrongVolumeKernel.floopy /exthome/andreas/._occa/loopy2_7d27af49ef7c8cc7.ocl
sh: 1: floopy: not found
Found cached binary of [/exthome/andreas/._occa/loopy2_7d27af49ef7c8cc7.ocl] in [/exthome/andreas/._occa/9dc467c8d2d13cc6]
...
```

I'd argue it should stop when it fails to execute floopy.

**Comment by dmed256** [comment]
I'm already detecting whether the system call returned an error and stops if it encounters an error:

```
#if (OCCA_OS == LINUX_OS) || (OCCA_OS == OSX_OS)
    const int compileError = system(sCommand.c_str());
#else
    const int compileError = system(("\"" +  sCommand + "\"").c_str());
#endif

    if(compileError)
      OCCA_CHECK(false, "Compilation error");
```

I'll see how to detect the sh error:

```
sh: 1: floopy: not found
```

**Comment by dmed256** [comment]
Closing this since [not found] can't be detected from system()

**Comment by inducer** [comment]
Quoting from the `system(3)` manpage:
```
*  If  a  shell  could  not  be executed in the child process, then the
   return value is as though the  child  shell  terminated  by  calling
   _exit(2) with the status 127.
```

So:

```
$ sh -c yoink ; echo $?
sh: 1: yoink: not found
127
```

**Comment by dmed256** [comment]
I meant the system() call quoted above, not in general

The system() check was already there when you submitted the issue, so I can't see what else can be added

**Comment by dmed256** [comment]
I get:
    loopy --lang=loopy --occa-defines=/Users/dsm5/._occa/loopy1_1cab4d2fe7914061.defs  --occa-add-dummy-arg addVectors.okl /Users/dsm5/._occa/loopy2_1cab4d2fe7914061.ocl
    sh: loopy: command not found
    
    ---[ Error ]--------------------------------------------
        File     : /Users/dsm5/gitRepos/night/src/occaBase.cpp
        Function : buildKernelFromLoopy
        Line     : 1611
        Error    : Compilation error
    ========================================================
    Abort trap: 6

so it does do the check correctly (not sure what's different on your system, maybe an old version of OCCA)

**Comment by inducer** [comment]
Probably old version in that case. Sorry about the noise..
