### ISSUE TITLE
floopy is now called loopy

### ISSUE THREAD

**Issue by inducer** [tcew/OCCA2#36]
The floopy transform executable is now just called `loopy`, not `floopy`. It also no longer takes a `--target` flag.

**Comment by dmed256** [comment]
Please provide the command you want to run

**Comment by dmed256** [comment]
Right now OCCA is executing

```
floopy --lang={loopy,floopy} --target=cl;0,0 --occa-defines={stuff} --occa-add-dummy-arg filename output
```

Will the following work?

```
loopy --occa-defines={stuff} --occa-add-dummy-arg filename output
```

**Comment by inducer** [comment]
Add `--lang=fortran` (for .floopy) and `--lang=loopy` (for .loopy), and it should work.

**Comment by dmed256** [comment]
Added it to [night], will merge after Travis CI passes

**Comment by inducer** [comment]
Thanks!
