### ISSUE TITLE
Memory leak in the C interface

### ISSUE THREAD

**Issue by jkozdon** [tcew/OCCA2#39]
In the C interface `occaKernelRun` there is a memory leak when "casted" occa types are used (such as `occaInt`).

For instance the following call
```c
occaKernelRun(some_kernel, occaInt(a), d_ptr);
```
will have a leak because 'occaInt' has a new without an associated delete.
 
From other places in the library, such as `occaKernelInfoAddDefine` the delete is issued in the call, so I assume that it make sense for the delete to be issued at the end of `occaKernelRun` (as opposed to a separate all by the user).

**Comment by dmed256** [comment]
Oops, good catch

Just pushed the update to the [night] branch and will merge with the main branch after Travis CI passes

Thanks!

**Comment by dmed256** [comment]
Ok, now occaType_t get's freed everywhere, except for one place:

If you use occaArgumentList_t and you add occaType_t to them, you need to manually free it using 

    occaArgumentListFree()

However, this is pretty much completely useless aside from adding more language front-ends

**Comment by jkozdon** [comment]
Perfect. Thanks!
