### ISSUE TITLE
fortran occaKernelInfoAddDefine with string argument

### ISSUE THREAD

**Issue by dshawul** [tcew/OCCA2#42]
I am in need of an occaKernelInfoAddDefine that is able to accept a string (character(len=*)) as its third argument, i.e for something like occaKernelInfoAddDefine(info,"datafloat","double"). The current fortran interface can only accept a "character" as its third argument, hence the above definition will result in "datafloat" being defined as just "d".
Thanks

**Comment by dmed256** [comment]
Lucas just fixed it, just merged it with the [master] branch

**Comment by dshawul** [comment]
Ok. Thank you.
