### ISSUE TITLE
Fortran occaKernelInfoAddDefine for double precision

### ISSUE THREAD

**Issue by dshawul** [tcew/OCCA2#43]
If I define a double precision kernel constant defined as :

gamma = 1.40023693379791_r8
call occaKernelInfoAddDefine(info, "p_Gamma", gamma)

Inside an occa kernel the constant is truncated to
gamma = 1.400240000000

I see that both versions with val = real(4) and real(8) are defined in occaF.f90 so there may be an issue in how the constant is stored for the later.

**Comment by dmed256** [comment]
I just reproduced it, I'll fix it right now
Also, further updates to OCCA will be in: https://github.com/libocca/occa

**Comment by dmed256** [comment]
Just fixed it in the (https://github.com/libocca/occa) repo

**Comment by dshawul** [comment]
Thank you. It works correctly now.

**Comment by dmed256** [comment]
No problem, thanks for the bug reports!
